In [1]:
import pickle
import numpy as np

In [2]:
clf=pickle.load(open("titanic_model.pkl","rb"))
ohe_sex=pickle.load(open("OHE_sex.pkl","rb"))
ohe_embarked=pickle.load(open("OHE_Embarked.pkl","rb"))

In [3]:
test_input=np.array([2,"male",32,40,0,"S"],dtype=object).reshape(1,6)

In [4]:
test_input

array([[2, 'male', 32, 40, 0, 'S']], dtype=object)

In [5]:
test_input_sex=ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\GR0012AU\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [6]:
test_input_sex

array([[1.]])

In [7]:
test_input_Embarked=ohe_embarked.transform(test_input[:,-1].reshape(1,1))

C:\Users\GR0012AU\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [8]:
test_input_Embarked

array([[0., 1.]])

In [9]:
test_input_transformed=np.concatenate((test_input[:,[0,3,4]],test_input[:,2].reshape(1,1),test_input_sex,test_input_Embarked),axis=1)

In [10]:
test_input_transformed

array([[2, 40, 0, 32, 1.0, 0.0, 1.0]], dtype=object)

In [12]:
clf.predict(test_input_transformed)

array([1], dtype=int64)