In [1]:
import pandas as pd
import numpy as numpy
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df=pd.read_csv(r"C:\Users\heman\Downloads\train.csv",usecols=["Survived","Age","Fare"])

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.impute import MissingIndicator

In [6]:
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=["Survived"],axis=1),df["Survived"],test_size=0.2,random_state=42)

In [7]:
x_train.isnull().sum()

Age     140
Fare      0
dtype: int64

In [9]:
x_test.isnull().sum()

Age     37
Fare     0
dtype: int64

In [10]:
SI=SimpleImputer()

In [12]:
x_train_trf=SI.fit_transform(x_train)
x_test_trf=SI.transform(x_test)

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
LG=LogisticRegression()
LG.fit(x_train_trf,y_train)

LogisticRegression()

In [18]:
y_pred=LG.predict(x_test_trf)

In [19]:
from sklearn.metrics import accuracy_score

In [20]:
print(accuracy_score(y_test,y_pred))

0.6480446927374302


In [21]:
# specifying Missing indicator

In [22]:
SIM=SimpleImputer(add_indicator=True)

In [24]:
x_train_SIM=SIM.fit_transform(x_train)
x_test_SIm=SIM.transform(x_test)

In [28]:
x_train_SIM

array([[ 45.5   ,  28.5   ,   0.    ],
       [ 23.    ,  13.    ,   0.    ],
       [ 32.    ,   7.925 ,   0.    ],
       ...,
       [ 41.    ,  14.1083,   0.    ],
       [ 14.    , 120.    ,   0.    ],
       [ 21.    ,  77.2875,   0.    ]])

In [29]:
x_test_SIm

array([[ 29.49884615,  15.2458    ,   1.        ],
       [ 31.        ,  10.5       ,   0.        ],
       [ 20.        ,   7.925     ,   0.        ],
       [  6.        ,  33.        ,   0.        ],
       [ 14.        ,  11.2417    ,   0.        ],
       [ 26.        ,  78.85      ,   0.        ],
       [ 29.49884615,   7.75      ,   1.        ],
       [ 16.        ,  18.        ,   0.        ],
       [ 16.        ,   7.75      ,   0.        ],
       [ 19.        ,  26.2833    ,   0.        ],
       [ 37.        ,  53.1       ,   0.        ],
       [ 44.        ,   8.05      ,   0.        ],
       [ 29.49884615,  25.4667    ,   1.        ],
       [ 30.        ,   7.225     ,   0.        ],
       [ 36.        ,  13.        ,   0.        ],
       [ 16.        ,  39.4       ,   0.        ],
       [ 42.        ,  52.5542    ,   0.        ],
       [ 29.49884615,   7.8292    ,   1.        ],
       [ 27.        ,  13.        ,   0.        ],
       [ 47.        ,  52.     

In [30]:
LGS=LogisticRegression()

In [31]:
LGS.fit(x_train_SIM,y_train)

LogisticRegression()

In [32]:
Y_pred_sim=LGS.predict(x_test_SIm)

In [33]:
print(accuracy_score(y_test,Y_pred_sim))

0.6368715083798883


In [34]:
mi=MissingIndicator()

In [35]:
mi.fit(x_train)

MissingIndicator()

In [36]:
x_train_mi=mi.transform(x_train)

In [37]:
x_test_mi=mi.transform(x_test)

In [38]:
x_train_mi

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [39]:
x_test_mi

array([[ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [40]:
x_train["missing_indicator"]=x_train_mi
x_test["missing_indicator"]=x_test_mi

In [44]:
x_train.sample(5)

,Age,Fare,missing_indicator
297,2.0,151.550,False
741,36.0,78.850,False
366,60.0,75.250,False
728,25.0,26.000,False
719,33.0,7.775,False


In [45]:
x_test.sample(5)

,Age,Fare,missing_indicator
837,NaN,8.0500,True
292,36.0,12.8750,False
670,40.0,39.0000,False
493,71.0,49.5042,False
854,44.0,26.0000,False
