In [1]:
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import load_diabetes

In [3]:
x,y=load_diabetes(return_X_y=True)

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
from sklearn.linear_model import SGDRegressor

In [9]:
reg=SGDRegressor(penalty="l2",max_iter=500,eta0=0.1,learning_rate="constant",alpha=0.001)

In [10]:
reg.fit(x_train,y_train)

SGDRegressor(alpha=0.001, eta0=0.1, learning_rate='constant', max_iter=500)

In [11]:
from sklearn.metrics import r2_score

In [12]:
y_pred=reg.predict(x_test)

In [13]:
print(r2_score(y_test,y_pred))

0.4409658923733599


In [15]:
print(reg.coef_)
print(reg.intercept_)

[  51.8122618  -123.06675636  386.56105031  258.99042678  -26.5909787
  -65.36527449 -178.88452653  133.73131388  293.21371306  125.67489266]
[146.04534123]


In [36]:
class MeraRidgeSGD:
    def __init__(self,alpha=0.001,epochs=50,learning_rate=0.01):
        self.alpha=alpha
        self.epochs=epochs
        self.learning_rate=learning_rate
        self.coef_=None
        self.intercept_=None

    def fit(self,x_train,y_train):
        self.coef_=np.ones(x_train.shape[1])
        self.intercept_=0
        # print(self.coef_)
        theta=np.insert(self.coef_,0,self.intercept_)
        # print(theta)
        x_train=np.insert(x_train,0,1,axis=1)
        
        for i in range(self.epochs):
            theta_der=np.dot(x_train.T,x_train).dot(theta) - np.dot(x_train.T,y_train) +self.alpha*theta
            theta=theta- self.learning_rate*theta_der
        self.intercept_=theta[0]
        self.coef_=theta[1:]

    def predict(self,x_test):
        return np.dot(x_test,self.coef_)+self.intercept_

In [95]:
m=MeraRidgeSGD(0.001,500,0.00458)

In [96]:
x_train[0]

array([ 0.07076875,  0.05068012,  0.01211685,  0.0563009 ,  0.03420581,
        0.04941617, -0.03971921,  0.03430886,  0.02736405, -0.0010777 ])

In [97]:
np.insert(x_train,0,1,axis=1)[0]

array([ 1.        ,  0.07076875,  0.05068012,  0.01211685,  0.0563009 ,
        0.03420581,  0.04941617, -0.03971921,  0.03430886,  0.02736405,
       -0.0010777 ])

In [98]:
m.fit(x_train,y_train)

In [99]:
m.predict(x_test)

array([144.61614915, 175.12756228, 143.71308339, 286.96017224,
       127.49594952, 101.54024135, 249.61324576, 193.19852351,
        90.90041553, 117.70850932,  97.53589458, 152.09202126,
        66.1502499 , 209.82531082, 108.10019622, 135.91356668,
       223.21373121, 245.72543152, 191.0527239 , 212.71458476,
       197.18358533,  91.09166971,  78.09861356, 188.56367865,
       152.28923374, 165.03382916, 186.71877542, 176.10685253,
        53.04769076, 120.18814996, 178.78839368,  95.37905277,
       134.59817429, 182.44353   , 173.42077735, 189.0587743 ,
       128.99691259, 126.68757328, 155.9070289 ,  62.69137289,
        84.19301725, 114.24472843, 157.91096785, 156.43367074,
       172.8552521 ,  67.32930308,  83.5195266 , 105.70559229,
        63.15393696, 152.74323747, 149.78720821,  66.49006221,
       118.90265428, 110.52092427, 171.2360146 , 152.07076551,
       100.87675328, 200.93907801, 114.60495427,  69.53895886,
       183.15280551, 192.72281245, 140.77806885, 114.48

In [100]:
print(m.coef_)
print(m.intercept_)

[  44.65390953 -183.50666963  486.35580926  314.88143702  -59.36040677
 -108.04969088 -212.24345226  145.20512621  361.1900671   124.5850281 ]
151.43088673646636


In [101]:
print(r2_score(y_test,m.predict(x_test)))

0.4593181458126281
